export const openedJobs = [
  {
    id: "1a2b3c4d",
    jobTitle: "Full-Stack Developer",
    jobDepartment: "Engineering",
    jobLocation: "San Francisco, CA",
    jobType: "Full-Time",
    jobDescription:
      "As a Full-Stack Developer, you will be responsible for developing and maintaining scalable web applications using modern frameworks. You will work closely with designers and product managers to implement innovative solutions for complex challenges, ensuring high performance and responsiveness of applications. This role requires an individual who is passionate about coding, eager to learn, and able to work collaboratively in a fast-paced environment.",
    jobResponsibilities: [
      "Design, develop, and deploy front-end and back-end services.",
      "Collaborate with designers and product teams to create user-friendly solutions.",
      "Write clean, efficient, and testable code while adhering to industry best practices.",
      "Optimize applications for maximum speed and scalability.",
      "Troubleshoot and debug issues across the stack.",
    ],
    jobQualifications: [
      "Bachelor’s degree in Computer Science or equivalent experience.",
      "Strong understanding of web development principles and best practices.",
      "Proficiency in both front-end and back-end technologies.",
    ],
    jobSkills: [
      "JavaScript",
      "React",
      "Node.js",
      "SQL",
      "REST APIs",
      "Git",
      "AWS",
    ],
    jobExperience: "3+ years of experience in full-stack development.",
    jobEducation:
      "BSc in Computer Science, Software Engineering, or a related field.",
    jobCompensation: "Competitive salary with benefits, equity, and bonus.",
    jobStatus: "Open",
    numberOfApplicants: 12,
    jobLink: "https://company.jobs/fullstack-developer",
  },
  {
    id: "2e3f4g5h",
    jobTitle: "Data Scientist",
    jobDepartment: "Data Analytics",
    jobLocation: "New York, NY",
    jobType: "Remote",
    jobDescription:
      "As a Data Scientist, you will analyze and interpret complex datasets to drive informed decision-making across various business functions. You will develop predictive models, create visualizations, and provide actionable insights to stakeholders. This role is ideal for someone with a strong analytical mindset, excellent problem-solving skills, and a passion for turning data into strategic opportunities.",
    jobResponsibilities: [
      "Develop predictive models and algorithms to solve business challenges.",
      "Clean, organize, and preprocess datasets for analysis.",
      "Communicate findings through detailed reports and compelling visualizations.",
      "Collaborate with cross-functional teams to align data initiatives with business goals.",
    ],
    jobQualifications: [
      "Proficiency in machine learning frameworks and statistical methods.",
      "Strong problem-solving and analytical skills.",
      "Ability to communicate data insights effectively.",
    ],
    jobSkills: [
      "Python",
      "R",
      "SQL",
      "TensorFlow",
      "Power BI",
      "Data Visualization",
    ],
    jobExperience: "2+ years of experience in data analysis or a related role.",
    jobEducation: "Master’s degree in Data Science, Statistics, or equivalent.",
    jobCompensation: "$90,000 - $120,000 annually with remote perks.",
    jobStatus: "Open",
    numberOfApplicants: 20,
    jobLink: "https://company.jobs/data-scientist",
  },
  {
    id: "3i4j5k6l",
    jobTitle: "DevOps Engineer",
    jobDepartment: "Operations",
    jobLocation: "Austin, TX",
    jobType: "Full-Time",
    jobDescription:
      "As a DevOps Engineer, you will be responsible for automating and streamlining development and deployment processes. You will work closely with engineering teams to improve system performance, scalability, and reliability. This role requires expertise in cloud platforms, infrastructure as code, and modern DevOps practices to ensure seamless integration and deployment workflows.",
    jobResponsibilities: [
      "Build and maintain CI/CD pipelines to support the development process.",
      "Monitor and optimize system performance to ensure high availability.",
      "Collaborate with development and operations teams to define system requirements.",
      "Troubleshoot complex system and infrastructure issues.",
    ],
    jobQualifications: [
      "Experience with cloud platforms and infrastructure as code tools.",
      "Strong knowledge of containerization and orchestration technologies.",
      "Excellent troubleshooting and problem-solving skills.",
    ],
    jobSkills: [
      "Docker",
      "Kubernetes",
      "Jenkins",
      "Terraform",
      "AWS",
      "Bash scripting",
    ],
    jobExperience: "4+ years in DevOps or related roles.",
    jobEducation:
      "Bachelor’s degree in Computer Science or relevant certifications.",
    jobCompensation: "$100,000 - $130,000 annually with relocation assistance.",
    jobStatus: "Open",
    numberOfApplicants: 8,
    jobLink: "https://company.jobs/devops-engineer",
  },
  // Additional job entries would follow the same pattern with unique ids and enhanced descriptions.
];

export const closedJobs = [
  {
    id: "973e4c98-dcc7-44e7-80ab-2cc6eb2e34a3",
    jobTitle: "Backend Developer",
    jobDepartment: "Engineering",
    jobLocation: "Chicago, IL",
    jobType: "Full-Time",
    jobDescription:
      "Develop and maintain backend systems with a focus on scalability and performance.",
    jobResponsibilities: [
      "Build APIs and services for web and mobile applications.",
      "Integrate third-party services and APIs.",
      "Optimize database queries and manage migrations.",
    ],
    jobQualifications: [
      "Strong experience with backend frameworks.",
      "Proficiency in database management.",
      "Knowledge of RESTful API design.",
    ],
    jobSkills: ["Node.js", "Express.js", "PostgreSQL", "Redis", "Docker"],
    jobExperience: "3+ years in backend development.",
    jobEducation: "BSc in Computer Science or a related field.",
    jobCompensation: "$90,000 - $110,000 annually with benefits.",
    jobStatus: "Closed",
    numberOfApplicants: 25,
    jobLink: "https://company.jobs/backend-developer",
  },
  {
    id: "abe6ef7c-4a21-44b2-b328-8cc03e3ef519",
    jobTitle: "Mobile App Developer",
    jobDepartment: "Engineering",
    jobLocation: "Boston, MA",
    jobType: "Full-Time",
    jobDescription:
      "Design and develop high-quality mobile applications for iOS and Android.",
    jobResponsibilities: [
      "Develop cross-platform mobile applications.",
      "Collaborate with product and design teams to deliver user-friendly apps.",
      "Debug and optimize mobile apps for performance.",
    ],
    jobQualifications: [
      "Experience with mobile app frameworks.",
      "Proficiency in both iOS and Android development.",
      "Knowledge of mobile app deployment processes.",
    ],
    jobSkills: ["React Native", "Swift", "Kotlin", "Redux", "Firebase"],
    jobExperience: "2+ years in mobile app development.",
    jobEducation: "Degree in Computer Science or related field.",
    jobCompensation: "$85,000 - $105,000 annually.",
    jobStatus: "Closed",
    numberOfApplicants: 18,
    jobLink: "https://company.jobs/mobile-app-developer",
  },
  {
    id: "c5a2c2b7-e47e-4d52-89b3-ea6343b6795b",
    jobTitle: "IT Support Specialist",
    jobDepartment: "IT",
    jobLocation: "Los Angeles, CA",
    jobType: "Part-Time",
    jobDescription:
      "Provide technical support to employees and maintain IT infrastructure.",
    jobResponsibilities: [
      "Troubleshoot hardware and software issues.",
      "Manage IT inventory and procurement.",
      "Ensure network and system uptime.",
    ],
    jobQualifications: [
      "Experience in technical support roles.",
      "Strong knowledge of IT systems and networks.",
      "Excellent communication and problem-solving skills.",
    ],
    jobSkills: [
      "Windows",
      "MacOS",
      "Active Directory",
      "Networking",
      "Help Desk Tools",
    ],
    jobExperience: "1+ years in IT support or related role.",
    jobEducation: "Certification in IT Support or related field.",
    jobCompensation: "$20 - $30/hour.",
    jobStatus: "Closed",
    numberOfApplicants: 10,
    jobLink: "https://company.jobs/it-support-specialist",
  },
  {
    id: "d18a2d36-0b7a-4905-8815-e8d25361c0c4",
    jobTitle: "Digital Marketing Specialist",
    jobDepartment: "Marketing",
    jobLocation: "Remote",
    jobType: "Contract",
    jobDescription:
      "Develop and execute digital marketing strategies to increase brand awareness.",
    jobResponsibilities: [
      "Manage social media campaigns and analytics.",
      "Optimize website SEO and content marketing.",
      "Develop and implement email marketing strategies.",
    ],
    jobQualifications: [
      "Experience in digital marketing.",
      "Strong understanding of SEO and SEM principles.",
      "Ability to analyze and report marketing metrics.",
    ],
    jobSkills: [
      "Google Ads",
      "SEO Tools",
      "Email Marketing",
      "Content Creation",
      "Analytics",
    ],
    jobExperience: "2+ years in digital marketing.",
    jobEducation: "Degree in Marketing, Business, or related field.",
    jobCompensation: "$35/hour with a 3-month contract.",
    jobStatus: "Closed",
    numberOfApplicants: 22,
    jobLink: "https://company.jobs/digital-marketing-specialist",
  },
];
