export const openedJobs = [
  {
    jobTitle: "Full-Stack Developer",
    jobDepartment: "Engineering",
    jobLocation: "San Francisco, CA",
    jobType: "Full-Time",
    jobDescription:
      "Develop and maintain scalable web applications using modern frameworks.",
    jobResponsibilities: [
      "Design, develop, and deploy front-end and back-end services.",
      "Collaborate with designers and product teams.",
      "Write clean, efficient, and testable code.",
    ],
    jobQualifications: [
      "Bachelor’s degree in Computer Science or equivalent experience.",
      "Strong understanding of web development principles.",
      "Proficiency in both front-end and back-end technologies.",
    ],
    jobSkills: [
      "JavaScript",
      "React",
      "Node.js",
      "SQL",
      "REST APIs",
      "Git",
      "AWS",
    ],
    jobExperience: "3+ years of experience in full-stack development.",
    jobEducation:
      "BSc in Computer Science, Software Engineering, or a related field.",
    jobCompensation: "Competitive salary with benefits, equity, and bonus.",
    jobStatus: "Open",
    numberOfApplicants: 12,
    jobLink: "https://company.jobs/fullstack-developer",
  },
  {
    jobTitle: "Data Scientist",
    jobDepartment: "Data Analytics",
    jobLocation: "New York, NY",
    jobType: "Remote",
    jobDescription:
      "Analyze and interpret complex data to drive informed decision-making.",
    jobResponsibilities: [
      "Develop predictive models and algorithms.",
      "Clean and organize datasets for analysis.",
      "Present insights and findings to stakeholders.",
    ],
    jobQualifications: [
      "Proficiency in machine learning frameworks and statistical methods.",
      "Strong problem-solving and analytical skills.",
      "Ability to communicate data insights effectively.",
    ],
    jobSkills: [
      "Python",
      "R",
      "SQL",
      "TensorFlow",
      "Power BI",
      "Data Visualization",
    ],
    jobExperience: "2+ years of experience in data analysis or a related role.",
    jobEducation: "Master’s degree in Data Science, Statistics, or equivalent.",
    jobCompensation: "$90,000 - $120,000 annually with remote perks.",
    jobStatus: "Open",
    numberOfApplicants: 20,
    jobLink: "https://company.jobs/data-scientist",
  },
  {
    jobTitle: "DevOps Engineer",
    jobDepartment: "Operations",
    jobLocation: "Austin, TX",
    jobType: "Full-Time",
    jobDescription:
      "Automate and streamline development and deployment processes.",
    jobResponsibilities: [
      "Build and maintain CI/CD pipelines.",
      "Monitor and improve system performance.",
      "Collaborate with development and operations teams.",
    ],
    jobQualifications: [
      "Experience with cloud platforms and infrastructure as code tools.",
      "Strong knowledge of containerization and orchestration technologies.",
      "Excellent troubleshooting skills.",
    ],
    jobSkills: [
      "Docker",
      "Kubernetes",
      "Jenkins",
      "Terraform",
      "AWS",
      "Bash scripting",
    ],
    jobExperience: "4+ years in DevOps or related roles.",
    jobEducation:
      "Bachelor’s degree in Computer Science or relevant certifications.",
    jobCompensation: "$100,000 - $130,000 annually with relocation assistance.",
    jobStatus: "Open",
    numberOfApplicants: 8,
    jobLink: "https://company.jobs/devops-engineer",
  },
  {
    jobTitle: "UI/UX Designer",
    jobDepartment: "Design",
    jobLocation: "Seattle, WA",
    jobType: "Part-Time",
    jobDescription:
      "Create user-centered designs for web and mobile applications.",
    jobResponsibilities: [
      "Collaborate with developers to implement designs.",
      "Conduct user research and usability testing.",
      "Design intuitive interfaces and user workflows.",
    ],
    jobQualifications: [
      "Strong portfolio showcasing design skills.",
      "Ability to create responsive and accessible designs.",
      "Experience in user research and prototyping.",
    ],
    jobSkills: [
      "Figma",
      "Sketch",
      "Adobe XD",
      "HTML/CSS",
      "User Research",
      "Prototyping",
    ],
    jobExperience: "2+ years in UI/UX design.",
    jobEducation: "Degree in Design, Human-Computer Interaction, or similar.",
    jobCompensation: "$40 - $50/hour.",
    jobStatus: "Open",
    numberOfApplicants: 15,
    jobLink: "https://company.jobs/ui-ux-designer",
  },
  {
    jobTitle: "Cybersecurity Analyst",
    jobDepartment: "Security",
    jobLocation: "Remote",
    jobType: "Contract",
    jobDescription:
      "Monitor and safeguard company networks and systems against threats.",
    jobResponsibilities: [
      "Conduct risk assessments and vulnerability scans.",
      "Manage firewalls and intrusion detection systems.",
      "Respond to and investigate security incidents.",
    ],
    jobQualifications: [
      "Experience in network security and incident response.",
      "Strong understanding of cybersecurity frameworks.",
      "Ability to identify and mitigate security risks.",
    ],
    jobSkills: [
      "SIEM tools",
      "Firewalls",
      "VPN",
      "Cybersecurity frameworks (NIST, ISO 27001)",
    ],
    jobExperience: "3+ years in cybersecurity or IT security.",
    jobEducation: "Bachelor’s in Information Security or related field.",
    jobCompensation: "$50/hour with a 6-month contract.",
    jobStatus: "Open",
    numberOfApplicants: 10,
    jobLink: "https://company.jobs/cybersecurity-analyst",
  },
];

export const closedJobs = [
  {
    jobTitle: "Backend Developer",
    jobDepartment: "Engineering",
    jobLocation: "Chicago, IL",
    jobType: "Full-Time",
    jobDescription:
      "Develop and maintain backend systems with a focus on scalability and performance.",
    jobResponsibilities: [
      "Build APIs and services for web and mobile applications.",
      "Integrate third-party services and APIs.",
      "Optimize database queries and manage migrations.",
    ],
    jobQualifications: [
      "Strong experience with backend frameworks.",
      "Proficiency in database management.",
      "Knowledge of RESTful API design.",
    ],
    jobSkills: ["Node.js", "Express.js", "PostgreSQL", "Redis", "Docker"],
    jobExperience: "3+ years in backend development.",
    jobEducation: "BSc in Computer Science or a related field.",
    jobCompensation: "$90,000 - $110,000 annually with benefits.",
    jobStatus: "Closed",
    numberOfApplicants: 25,
    jobLink: "https://company.jobs/backend-developer",
  },
  {
    jobTitle: "Mobile App Developer",
    jobDepartment: "Engineering",
    jobLocation: "Boston, MA",
    jobType: "Full-Time",
    jobDescription:
      "Design and develop high-quality mobile applications for iOS and Android.",
    jobResponsibilities: [
      "Develop cross-platform mobile applications.",
      "Collaborate with product and design teams to deliver user-friendly apps.",
      "Debug and optimize mobile apps for performance.",
    ],
    jobQualifications: [
      "Experience with mobile app frameworks.",
      "Proficiency in both iOS and Android development.",
      "Knowledge of mobile app deployment processes.",
    ],
    jobSkills: ["React Native", "Swift", "Kotlin", "Redux", "Firebase"],
    jobExperience: "2+ years in mobile app development.",
    jobEducation: "Degree in Computer Science or related field.",
    jobCompensation: "$85,000 - $105,000 annually.",
    jobStatus: "Closed",
    numberOfApplicants: 18,
    jobLink: "https://company.jobs/mobile-app-developer",
  },
  {
    jobTitle: "IT Support Specialist",
    jobDepartment: "IT",
    jobLocation: "Los Angeles, CA",
    jobType: "Part-Time",
    jobDescription:
      "Provide technical support to employees and maintain IT infrastructure.",
    jobResponsibilities: [
      "Troubleshoot hardware and software issues.",
      "Manage IT inventory and procurement.",
      "Ensure network and system uptime.",
    ],
    jobQualifications: [
      "Experience in technical support roles.",
      "Strong knowledge of IT systems and networks.",
      "Excellent communication and problem-solving skills.",
    ],
    jobSkills: [
      "Windows",
      "MacOS",
      "Active Directory",
      "Networking",
      "Help Desk Tools",
    ],
    jobExperience: "1+ years in IT support or related role.",
    jobEducation: "Certification in IT Support or related field.",
    jobCompensation: "$20 - $30/hour.",
    jobStatus: "Closed",
    numberOfApplicants: 10,
    jobLink: "https://company.jobs/it-support-specialist",
  },
  {
    jobTitle: "Digital Marketing Specialist",
    jobDepartment: "Marketing",
    jobLocation: "Remote",
    jobType: "Contract",
    jobDescription:
      "Develop and execute digital marketing strategies to increase brand awareness.",
    jobResponsibilities: [
      "Manage social media campaigns and analytics.",
      "Optimize website SEO and content marketing.",
      "Develop and implement email marketing strategies.",
    ],
    jobQualifications: [
      "Experience in digital marketing.",
      "Strong understanding of SEO and SEM principles.",
      "Ability to analyze and report marketing metrics.",
    ],
    jobSkills: [
      "Google Ads",
      "SEO Tools",
      "Email Marketing",
      "Content Creation",
      "Analytics",
    ],
    jobExperience: "2+ years in digital marketing.",
    jobEducation: "Degree in Marketing, Business, or related field.",
    jobCompensation: "$35/hour with a 3-month contract.",
    jobStatus: "Closed",
    numberOfApplicants: 22,
    jobLink: "https://company.jobs/digital-marketing-specialist",
  },
];
