import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./(shared)/Navbar";

const brush = localFont({
  src: "../fonts/FontMesa - Regular.otf",
  variable: "--brush",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${brush.variable} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
